name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

env:
  SKIP_DEPLOYMENT: true  # Set to false when ready to enable deployment
  SKIP_DOCKER: true       # Set to false to enable docker build

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout code with Git LFS support
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Check for required model and image files
        shell: pwsh
        run: |
          echo "Checking files..."
          Get-ChildItem backend/model
          Get-ChildItem backend/tests/test_images

          if (-Not (Test-Path backend/model/model_unquant.tflite)) {
            Write-Error "Missing model file!" ; exit 1
          }
          if (-Not (Test-Path backend/tests/test_images/test_normal.jpg)) {
            Write-Error "Missing test image!" ; exit 1
          }

      - name: Run Backend Tests
        run: |
          cd backend/tests
          pytest

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x'

      - name: Build and Test Frontend
        run: |
          cd frontend/AnomalyDetector
          dotnet build
          dotnet test

      - name: Build Docker Image for Backend
        if: env.SKIP_DOCKER != 'true'
        run: |
          cd backend
          docker build -t anomaly-backend .

      - name: Deploy Backend to VM via SSH
        if: env.SKIP_DEPLOYMENT != 'true'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        shell: bash
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ashok@192.168.56.101 \
            "docker stop anomaly-backend || true && docker rm anomaly-backend || true && docker run -d --name anomaly-backend -p 8000:8000 anomaly-backend"
